### ISSUE TITLE
CRUD methods are not working correctly

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/modelserver#35]
The current CRUD endpoint implementation assumes that the last  segment of the request url is the file url (e.g ../api/v1/models/**Coffee.ecore**). This does only work for models that are located directly in the workspace root. When using absolute paths or models in subdirs the server does not recognize the request.

To solve this issue the file path should either be passed as an additional parameter or in the request body.

**Comment by edgarmueller** [comment]
Fixed via #42
