### ISSUE TITLE
CORS Issue when saving

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/modelserver#44]
Access to fetch at 'http://localhost:8081/api/v1/models/SuperBrewer3000.coffee' from origin 'http://localhost:3000' has been blocked by CORS policy: Method patch is not allowed by Access-Control-Allow-Methods in preflight response.

**Comment by edgarmueller** [comment]
Fixed via https://github.com/eclipsesource/modelserver-theia/pull/9
