### ISSUE TITLE
Nested paths are not properly supported by the create call

### ISSUE THREAD

**Issue by edgarmueller** [eclipsesource/modelserver#54]
E.g. calling create with `modeluri=test/test1.json` does create the `test1.json` file on the root level

**Comment by cdamus** [comment]
This seems to be working now in commit 49eb9e5faa9de594924dd6e2c31624e0ec80d749.  I can
* post a model URI with an arbitrary number of path segments; it is reported correctly by a `GET modeluris`
* `GET` a model with an arbitrary number of path segments
* see that the server returns an appropriate 404 when `GET`ting a model URI with path segments that don't exist
* see that the server loads on start-up an existing model from my workspace with some path, and I can retrieve its contents
